In [ ]:
 #task-1 creating and modifying an array

In [ ]:
arr=[3,7,8,6,9]
arr[3]=5
print("modified array",arr)

modified array [3, 7, 8, 5, 9]


In [ ]:
#task-2 finding min,max and mean

In [ ]:
import numpy as np
arr= ([9,4,1,8,5])
print("min:",np.min(arr))
print("max:",np.max(arr))
print("mean:",np.mean(arr))

min: 1
max: 9
mean: 5.4


In [ ]:
#task-3 reshaping and flattening an array

In [ ]:
import numpy as np
arr = np.arange(1, 13)
reshaped_arr = arr.reshape(4, 3)
print("Reshaped array", reshaped_arr)
flattened_arr = reshaped_arr.flatten()
print("Flattened Array:", flattened_arr)


Reshaped array [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#Task 4: Create two 2×2 arrays and stack them vertically & horizontally

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
vertical_stack = np.vstack((a,b))
horizontal_stack = np.hstack((a,b))
print("Vertically Stacked:\n", vertical_stack)
print("Horizontally Stacked:\n", horizontal_stack)

Vertically Stacked:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally Stacked:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Task 5: Convert a 1D array of size 9 into a 3×3 matrix

In [ ]:
a= np.arange(1, 10).reshape(3, 3)
print("3x3 Matrix:\n", a)

3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#task 6: Create an array from 1 to 10 and reverse it

In [ ]:
a = np.arange(1, 11)[::-1]
print("Reversed Array:", a)

Reversed Array: [10  9  8  7  6  5  4  3  2  1]
